= Modules
:toc:
:toclevels: 3

== Root Modules

Convenience modules that provides access to a selection of other modules.

=== `synodic.honesty`

Exports all other modules

---

== `Test` Modules

Library for unit testing and other testing utilities.

---

=== Public Modules

There are a variety of ways to interact with the testing library.

==== `synodic.honesty.test`

For defining and implementing tests.

==== `synodic.honesty.test.api`

Direct access to the test API

==== `synodic.honesty.test.commands`

Frontend for running tests from the command line. Includes an Instance entrypoint for all commands. Also includes wrappers for each individual command and subcommand with utilities to create your own

---

=== Private Modules

Modules that are used in multiple other, public modules that are not intended to be used directly by the user.

==== `synodic.honesty.test.backend`

The private infrastructure of the API module.

==== `synodic.honesty.test.entry`

The entrypoint for the library that defines the main function. Linking to the target generated with this module will automatically collect and run tests according to the default configuration.

---

=== Module Relationships

[mermaid]
....
flowchart LR
	Backend --> API
	Backend --> Test
	API --> CLI
	CLI --> Entry
....

