= Modules
:toc:
:toclevels: 3

== Root Modules

Convenience modules that provides access to a selection of other modules.

=== `synodic.honesty`

Exports all other modules

---

== `Test` Modules

Library for unit testing and other testing utilities.

---

=== Public Modules

There are a variety of ways to interact with the testing library.

==== `synodic.honesty.test`

For defining and implementing tests.

==== `synodic.honesty.test.api`

Direct access to the test API

==== `synodic.honesty.test.commands`

Frontend for running tests from the command line. Includes an Instance entrypoint for all commands and wrappers for each individual command and subcommand.

==== `synodic.honesty.test.schema`

Defines the plugin types that are used both internally and externally.

==== `synodic.honesty.test.types`

Defines the types used in the test, commands, and backend modules.

---

=== Private Modules

Modules that are used in multiple other, public modules that are not intended to be used directly by the user.

==== `synodic.honesty.test.core`

The top level module that defines core types and utilities for the test library.

==== `synodic.honesty.test.backend`

The private infrastructure of the API module.

==== `synodic.honesty.test.entry`

The entrypoint for the library that defines the main function. Linking to the target generated with this module will automatically collect and run tests according to the default configuration.

---

=== Module Relationships

[mermaid]
....
flowchart LR
	Schema --> Types
	Types --> Test
	Core --> Backend
	Core --> Types
	Backend --> API
	Schema --> Core
	Types --> Backend
	API --> Commands
	Commands --> Entry
....

